version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    env_file: 
      - .env
    
    depends_on: []

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        - VITE_PROD_API_URL=${VITE_PROD_API_URL}
    ports:
      - "4000:80"
    env_file:
      - .env
    depends_on:
      - server
