version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    env_file: .env
    
    depends_on: []

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - server
